[package]
name = "augustus"
version = "0.1.0"
edition = "2021"
rust-version = "1.75.0"

[workspace]
members = [
    ".",
    "crates/entropy",
    "tools/replication-control",
    "tools/replication-control-messages",
    "tools/entropy-control",
    "tools/entropy-control-messages",
]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.artifact]
inherits = "release"
debug = true
# strip = true
# lto = true

[dependencies]
anyhow = { version = "1.0.79", features = ["backtrace"] }
axum = "0.7.4"
bincode = "1.3.3"
bytes = "1.5.0"
crossbeam-queue = "0.3.11"
dashmap = "5.5.3"
derive_more = "0.99.17"
lru = "0.12.2"
primitive-types = "0.12.2"
rand = "0.8.5"
replication-control-messages = { version = "0.1.0", path = "tools/replication-control-messages" }
secp256k1 = { version = "0.28.1", features = ["rand-std", "serde"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.114"
sha2 = "0.10.8"
tokio = { version = "1.35.1", features = [
    "net",
    "time",
    "sync",
    "rt",
    "signal",
    "macros",
    "rt-multi-thread",
] }
tokio-util = "0.7.10"
