[package]
name = "augustus"
version = "0.1.0"
edition = "2021"
rust-version = "1.77.1"

[workspace]
members = [
    ".",
    "tools/replication-control",
    "tools/replication-control-messages",
    "tools/entropy-control",
    "tools/entropy-control-messages", 
    "tools/cover-control", 
    "tools/cover-control-messages",
]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.artifact]
inherits = "release"
# debug = true
strip = true
# lto = true

# cSpell:disable
[features]
ordinary = [
    "tikv-jemallocator",
    "nitro-enclaves",
    "reqwest",
]
nitro-enclaves = ["aws-nitro-enclaves-nsm-api", "aws-nitro-enclaves-attestation"]

[[bin]]
name = "entropy"
required-features = ["wirehair", "reqwest"]

[[bin]]
name = "cover"
required-features = ["nitro-enclaves"]

[[example]]
name = "nitro-enclaves-clock-validator"
required-features = ["nitro-enclaves"]

[[example]]
name = "cover-bench-clock"
required-features = ["nitro-enclaves"]

[dependencies]
anyhow = { version = "1.0.79", features = ["backtrace"] }
axum = { version = "0.7.4", features = ["multipart"] }
bincode = "1.3.3"
blake2 = "0.10.6"
bytes = "1.5.0"
crossbeam-queue = "0.3.11"
derive_more = "0.99.17"
derive-where = "1.2.7"
hdrhistogram = "7.5.4"
lru = "0.12.2"
nix = { version = "0.28.0", features = ["socket", "sched", "resource"] }
primitive-types = { version = "0.12.2", features = ["serde"] }
quinn = { git = "https://github.com/quinn-rs/quinn", version = "0.11.0" }
rand = "0.8.5"
rand_distr = "0.4.3"
rcgen = { git = "https://github.com/rustls/rcgen", version = "0.13.0", features = [
    "x509-parser",
] }
rusqlite = { version = "0.31.0", features = ["bundled"] }
rustc-hash = "1.1.0"
rustls = { version = "0.21.0", default-features = false, features = ["quic"] }
serde = { version = "1.0.195", features = ["derive"] }
tikv-jemallocator = { version = "0.5.4", optional = true }
tokio = { version = "1.35.1", features = ["net", "time", "sync", "rt", "signal", "macros", "rt-multi-thread", "fs"] }
tokio-util = "0.7.10"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
schnorrkel = { version = "0.11.4", features = ["serde"] }
secp256k1 = { version = "0.29.0", features = ["rand-std", "serde"] }
serde_json = "1.0.114"
sha2 = "0.10.8"
scc = "2.0.19"

cover-control-messages = { version = "0.1.0", path = "tools/cover-control-messages" }
aws-nitro-enclaves-nsm-api = { version = "0.4.0", optional = true }
aws-nitro-enclaves-attestation = { git = "https://github.com/neatsys/aws-nitro-enclaves-attestation", version = "0.1.0", optional = true }

entropy-control-messages = { version = "0.1.0", path = "tools/entropy-control-messages" }
wirehair = { git = "https://github.com/neatsys/wirehair", version = "0.1.2", optional = true }
reqwest = { version = "0.12.4", features = ["json", "multipart"], optional = true }

replication-control-messages = { version = "0.1.0", path = "tools/replication-control-messages" }

[dev-dependencies]
proptest = "1.4.0"
