[package]
name = "augustus"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "tools/*"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
anyhow = { version = "1.0.79", features = ["backtrace"] }
axum = "0.7.4"
bincode = "1.3.3"
bytes = "1.5.0"
derive_more = "0.99.17"
rand = "0.8.5"
replication-control-messages = { version = "0.1.0", path = "tools/replication-control-messages" }
secp256k1 = { version = "0.28.1", features = ["serde"] }
serde = { version = "1.0.195", features = ["derive"] }
sha2 = "0.10.8"
tokio = { version = "1.35.1", features = ["net", "time", "sync", "rt", "signal", "macros", "rt-multi-thread"] }
tokio-util = "0.7.10"
