[package]
name = "augustus"
version = "0.1.0"
edition = "2021"
rust-version = "1.77.1"

[workspace]
members = [
    ".",
    # "crates/entropy",
    "tools/replication-control",
    "tools/replication-control-messages",
    "tools/entropy-control",
    "tools/entropy-control-messages",
]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.artifact]
inherits = "release"
strip = true
# lto = true
# debug = true

# cSpell:disable
[dependencies]
anyhow = { version = "1.0.79", features = ["backtrace"] }
axum = "0.7.4"
bincode = "1.3.3"
bytes = "1.5.0"
derive_more = "0.99.17"
derive-where = "1.2.7"
rand = "0.8.5"
rustix = { version = "0.38.31", features = ["process"] }
serde = { version = "1.0.195", features = ["derive"] }
tokio = { version = "1.35.1", features = [
    "net",
    "time",
    "sync",
    "rt",
    "signal",
    "macros",
    "rt-multi-thread",
] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
# search
crossbeam-queue = "0.3.11"
rustc-hash = "1.1.0"
tikv-jemallocator = "0.5.4"
# kademlia net
lru = "0.12.2"
primitive-types = { version = "0.12.2", features = ["serde"] }
# app::ycsb
rand_distr = "0.4.3"
# app::sqlite
rusqlite = { version = "0.31.0", features = ["bundled"] }
# crypto
schnorrkel = { version = "0.11.4", features = ["serde"] }
secp256k1 = { version = "0.28.1", features = ["rand-std", "serde"] }
sha2 = "0.10.8"
# human readable op/result of some apps
serde_json = "1.0.114"
# bulk and artifacts
tokio-util = "0.7.10"
# QUIC net
quinn = { git = "https://github.com/quinn-rs/quinn", version = "0.11.0" }
rustls = { version = "0.21.0", default-features = false, features = ["quic"] }
# certificate
rcgen = { git = "https://github.com/rustls/rcgen", version = "0.13.0", features = [
    "x509-parser",
] }

replication-control-messages = { version = "0.1.0", path = "tools/replication-control-messages" }
scc = "2.0.19"

[dev-dependencies]
proptest = "1.4.0"
